### ISSUE TITLE
Change syncSource param to be a list of seeds

### ISSUE THREAD

**Issue by gortiz** [torodb/stampede#189]
At this moment, ToroDB Stampede has a configuration parameter called syncSource whose value is the seed Stampede uses to discover other nodes on the replica set. As explained on the [devel email group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/torodb-dev/rIcCDUdQHk4), it may be a failure point if Stampede starts up when that sync source is down. To deal with that, the user needs to provide some scripts to detect the situation and then start Stampede with another seed. It would be nice to change the syncSource parameter to a list of seeds, so if the first one does not respond, Stampede would try the next one.

**Comment by teoincontatto** [comment]
#193
