### ISSUE TITLE
Keyfile Replica Auth

### ISSUE THREAD

**Issue by dookehster** [torodb/stampede#201]
You folks seem to work well with X.509, however, there isn't any love for keyfile auth. Any chance that'll change?

**Comment by dookehster** [comment]
Specifically, seeing: 
Aug 11 21:43:34 localhost torodb-stampede[23405]: 2017-08-11T09:43:34.207 ERROR REPL       - Fatal error while starting recovery mode: Error while inserting a cloned document

After:
Aug 11 21:43:32 localhost torodb-stampede[23405]: 2017-08-11T09:43:32.590 WARN  REPL       - Error in heartbeat request to arbiter-mongo-live01:27017; {errCode :UNAUTHORIZED, errorMsg:Command failed with error 13: 'not authorized on admin to execute command { replSetHeartbeat: "<MY SERVER>", pv: 1, v: 21, from: "" }' on server <MY SERVER>:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on admin to execute command { replSetHeartbeat: \"<MY SERVER>\", pv: 1, v: 21, from: \"\" }", "code" : 13 }}

**Comment by teoincontatto** [comment]
Hello @dookehster,

If I am understanding correctly you are trying to authenticate ToroDB Stampede using keyfile authentication. This kind of authentication mechanism is just for internal authentication between replica set members and Stampede connect as a regular client. Please look at following link to ToroDB Stampede documentation to configure authentication to a Replica Set for ToroDB Stampede:

[https://www.torodb.com/stampede/docs/1.0.0-beta3/configuration/mongodb-connectivity/](https://www.torodb.com/stampede/docs/1.0.0-beta3/configuration/mongodb-connectivity/)
