### ISSUE TITLE
Trying to build Stampede from source results in error

### ISSUE THREAD

**Issue by mr-sk** [torodb/stampede#210]
Hello, 

I have another issue open (https://github.com/torodb/stampede/issues/205), and the stated fix is to build from source. I attempted to do so by following the instructions and on this step it fails:

```
➜  stampede git:(master) mvn clean package -P assembler,prod
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.torodb.stampede:stampede-pom:1.0.0-SNAPSHOT: Could not find artifact com.torodb:parent-pom:pom:1.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.torodb.stampede:stampede-pom:1.0.0-SNAPSHOT (/private/tmp/stampede/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.torodb.stampede:stampede-pom:1.0.0-SNAPSHOT: Could not find artifact com.torodb:parent-pom:pom:1.0.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

Any help is appreciated. Thanks!

**Comment by teoincontatto** [comment]
Hi @mr-sk,

Thanks for pointing this out. Since all of our project use a parent pom in another repository when we build the development branch we deploy it to sonatype. But the sonatype repository is defined in the parent pom that is not installed yet.

The strange thing is that on travis-ci this is working and I can not find a clear explication (maybe it is cached).

As a workaround you should be able to build by installing the required parent pom from sonatype using following command from a folder out of the project (this is because otherwise it will fail with the same error you mentioned):

```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.4:get \
  -DremoteRepositories=https://oss.sonatype.org/content/groups/public \
  -Dartifact=com.torodb:parent-pom:1.0.1-SNAPSHOT:pom
```

**Comment by JessKane** [comment]
Hey @teoincontatto  ,

I'm a coworker of @mr-sk , following up on this. Installing the sonatype parent pom did solve the initial problem, but the build still fails. It appears to be auth related? 

<img width="772" alt="screen shot 2017-09-20 at 12 07 37 pm" src="https://user-images.githubusercontent.com/1624545/30654717-b61debee-9dfc-11e7-8724-e8fb670f8f5d.png">

Thanks!

**Comment by teoincontatto** [comment]
Hi @JessKane,

It seems this is due to some issues with the docker-maven-plugin. Please try to re-run the build including the flag `-Ddocker.skip`.
