### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by chinmay185** [torodb/stampede#212]
The following two links from README.md are broken and return a 404 page.
1. how to use (https://www.torodb.com/stampede/docs/how-to-use)
2. Development Setup - Documentation (https://www.torodb.com/stampede/docs/installation/previous-requirements/)

**Comment by teoincontatto** [comment]
Hello @chinmay185,

Thanks for reporting the issue. We have updated our Web configuration to fix those links.

Cheers
