### ISSUE TITLE
Warning when arbiter is present

### ISSUE THREAD

**Issue by sgiacomel** [torodb/stampede#213]
Hi,
first of all, thanks for your work! ToroDB is awesome!
I have an issue replicating from a cluster composed of 4 "Regular" hosts and an arbiter.
The replication works fine and I'm impressed with the speed. The only annoying part is a list of messages like:

` WARN  REPL       'topology-executor-0'          m.r.t.TopologyHeartbeatHandler - Error in heartbeat request to arbiter:27019; {errCode :HOST_UNREACHABLE, errorMsg:com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=arbiter:27019, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=null, userName='stampede', source='admin', password=<hidden>, mechanismProperties={}}}, caused by {com.mongodb.MongoCommandException: Command failed with error 18: 'Authentication failed.' on server arbiter:27019. The full response is { "ok" : 0.0, "errmsg" : "Authentication failed.", "code" : 18, "codeName" : "AuthenticationFailed" }}}]}`

or 

`08:41:52.576 WARN  REPL       'topology-executor-0'          m.r.t.TopologyHeartbeatHandler - Error in heartbeat request to arbiter:27019; {errCode :UNAUTHORIZED, errorMsg:Command failed with error 13: 'not authorized on admin to execute command { replSetHeartbeat: "sensibill_beta_staging", pv: 1, v: 11, from: "" }' on server arbiter:27019. The full response is { "ok" : 0.0, "errmsg" : "not authorized on admin to execute command { replSetHeartbeat: \"sensibill_beta_staging\", pv: 1, v: 11, from: \"\" }", "code" : 13, "codeName" : "Unauthorized" }}
`

is there a way to exclude the arbiter from the sync?
Thanks

**Comment by ahachete** [comment]
Hi @sgiacomel Sorry for my late reply.

Certainly this is just a warning, it doesn't have any issue in production. But we will patch this for the next version. Thank you for your interest and reports!

**Comment by porimol** [comment]
@ahachete 
Same things happening with us. You are claiming that it will not be an issue in production but truly speaking that I cannot migrating data. Its always throwing that errors!

**Comment by ahachete** [comment]
Hmmm, a warning should not stop replication. OK, adding it to the next release goals, by the end of the month we should wrap 1.0 GA.

**Comment by teoincontatto** [comment]
Hi @sgiacomel and @porimol,

We published the new version of [Stampede](https://github.com/torodb/stampede/releases/tag/v1.0.0).

**Comment by porimol** [comment]
@teoincontatto 

Thanks :+1: , I will upgrade to v1.0 soon :)
