### ISSUE TITLE
DBRefs are transformed into "_e" columns (embedded objects)

### ISSUE THREAD

**Issue by fer2d2** [torodb/stampede#219]
MongoDB has two strategies to create relationships between documents:

- ObjectId's
- DBRefs (https://docs.mongodb.com/manual/reference/database-references/#dbrefs)

Stampede treats DBRefs as if they were embedded objects and therefore inserts them as a boolean value in Postgres.

For example:

*MongoDB:*
![image](https://user-images.githubusercontent.com/11785050/47459897-8beb5480-d7dd-11e8-8d13-d0ec1a006eb7.png)

*Postgres output generated by Stampede:*
![image](https://user-images.githubusercontent.com/11785050/47459928-a45b6f00-d7dd-11e8-9141-8ad39dc676e9.png)

This prevents the MongoDB relationships created in this way from being used in Postgres.

**Comment by teoincontatto** [comment]
Hi @fer2d2,

Stampede create the boolean field with `_e` postfix when the actual value of the key is a document (or array of document) and then serialize it in another table (in this case should ends with the suffix `_jurisdiction`). The boolean value indicates if the row of this other table contains a document (false) or an array of documents (true).

**Comment by fer2d2** [comment]
Thank you very much, @teoincontatto !
