### ISSUE TITLE
ToroDB Stampede gives no output

### ISSUE THREAD

**Issue by georgemakrakis** [torodb/stampede#220]
In a Ubuntu 16.04 server running Mongo 3.4.18 and PostgreSQL 10.6 with all the steps at quick-start guide successfully made, when trying to run the  **torodb-stampede --ask-for-password** command inside the **torodb-stampede-1.0.0/bin** folder gives me no output. Any suggestions on this?

**Comment by teoincontatto** [comment]
Can you run the following command and post the output:

```
bash -x torodb-stampede --ask-for-password
```
