### ISSUE TITLE
When will mongo 3.6 be supported?

### ISSUE THREAD

**Issue by quique0194** [torodb/stampede#229]
ToroDB looks like a fantastic tool, but if mongoDB 3.6 is not supported soon, I will have to look in some other direction.

**Comment by teoincontatto** [comment]
Hi @quique0194, I'm sorry but currently we do not have any resources assigned to the project.

**Comment by livejake** [comment]
If I was going to look into upgrading torodb to support mongo 3.6, do you have any thoughts on how much work this would involve, how you've handled past db upgrades, known issues, the different repositories that where the code sits, any sections of code of particular interest.

**Comment by ahachete** [comment]
Hi @livejake We are no longer maintaining the project actively. If you would be willing to work on the upgrade yourself, that would be awesome!

The amount of work is related to the amount of new operations introduced as part of the replication process. I may be wrong, as I haven't looked into the details, but I believe bringing compatibility with 3.6 shouldn't be a lot of work. There are a few areas that need adjustment, and probably some operation may even be ignored. I would consider this doable.

However, MongoDB also introduced https://docs.mongodb.com/manual/changeStreams/ That would supposedly make it way easier to implement replication. But to replace the current replication mechanism by ChangeStreams would definitely be an invasive change. I would not follow this route, for now.

We will be happy to review any PR bringing compatibility with 3.6 :)

**Comment by esatterwhite** [comment]
Is this project dead?

**Comment by ahachete** [comment]
Unfortunately, it is no longer maintained, @esatterwhite.

**Comment by esatterwhite** [comment]
@ahachete That is a shame. The torodb tools look awesome and are exactly what I need.
is 8Kdata is an viable entity?
Why the lack of interest in this project?

**Comment by ahachete** [comment]
There has been not enough business interest into it. If there would be someone willing to come and fund its continued development, it could come back to life.

**Comment by asaf050** [comment]
Perhaps we should do some crowdfunding? How much fund does it require?

**Comment by esatterwhite** [comment]
Enable github sponsorships?

**Comment by sandeep-devarapalli** [comment]
Very interesting project, would like to work on this

**Comment by ahachete** [comment]
Any work towards adding more modern support would require, as of today, potentially, a significant (if not whole) rewrite. Closing issue.
