### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Luthien-in-edhil** [torodb/stampede#233]
Hi,

Reading about this project on https://www.torodb.com/ made me curious, but from the repository I get the impression that the project is not under active development right now because there haven't been any updates in the past three years. 
Is that correct?

**Comment by ahachete** [comment]
That's correct, unfortunately it is no longer maintained.

**Comment by Luthien-in-edhil** [comment]
Thanks. That's a pity, it looked interesting.
